**Linear algebra in Python with NumPy**


In [3]:
import numpy as np


In [4]:
# Difining lists and numpy arrays

alist = [1, 2, 3, 4, 5]
narray = np.array([1, 2, 3, 4, 5])

print(type(alist))
print(type(narray))

<class 'list'>
<class 'numpy.ndarray'>


**Algebraic operators on NumPy arrays vs. Python lists**

One of the common beginner mistakes is to mix up the concepts of NumPy arrays and Python lists. Just observe the next example, where we add two objects of the two mentioned types. Note that the '+' operator on NumPy arrays perform an element-wise addition, while the same operation on Python lists results in a list concatenation. Be careful while coding. Knowing this can save many headaches.

In [5]:
print(narray + narray)
print(alist + alist)

[ 2  4  6  8 10]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [6]:
print(narray * 3)
print(alist * 3)

[ 3  6  9 12 15]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


**Matrix or Array of Arrays**

In linear algebra, a matrix is a structure composed of n rows by m columns. That means each row must have the same number of columns. With NumPy, we have two ways to create a matrix:

Creating an array of arrays using np.array (recommended)

In [12]:
npmatrix1 = np.array([narray, narray, narray])
print(npmatrix1)
npmatrix2 = np.array([alist, alist, alist]) # Matrix initialized with lists
npmatrix3 = np.array([narray, [1, 1, 1, 1], narray]) # Matrix initialized with both types

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


C:\Users\Mit\AppData\Local\Temp\ipykernel_9824\2130772522.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  npmatrix3 = np.array([narray, [1, 1, 1, 1], narray]) # Matrix initialized with both types


**Scaling and translating matrices**



In [14]:
result = npmatrix1 * 2 + 1 # For each element in the matrix, multiply by 2 and add 1
print(result)

[[ 3  5  7  9 11]
 [ 3  5  7  9 11]
 [ 3  5  7  9 11]]


In [15]:
result = npmatrix1 * npmatrix1 # Multiply each element by itself
print(result)

[[ 1  4  9 16 25]
 [ 1  4  9 16 25]
 [ 1  4  9 16 25]]


**Transpose a matrix**


In [16]:
matrix3x2 = np.array([[1, 2], [3, 4], [5, 6]]) # Define a 3x2 matrix
print('Original matrix 3 x 2')
print(matrix3x2)
print('Transposed matrix 2 x 3')
print(matrix3x2.T)

Original matrix 3 x 2
[[1 2]
 [3 4]
 [5 6]]
Transposed matrix 2 x 3
[[1 3 5]
 [2 4 6]]


**Get the norm of a nparray or matrix**

In [17]:
nparray1 = np.array([1, 2, 3, 4]) # Define an array
norm1 = np.linalg.norm(nparray1)

nparray2 = np.array([[1, 2], [3, 4]]) # Define a 2 x 2 matrix. Note the 2 level of square brackets
norm2 = np.linalg.norm(nparray2) 

print(norm1)
print(norm2)

5.477225575051661
5.477225575051661


Note that without any other parameter, the norm function treats the matrix as being just an array of numbers. However, it is possible to get the norm by rows or by columns. The axis parameter controls the form of the operation:

1. axis=0 means get the norm of each column

2. axis=1 means get the norm of each row.

In [18]:
nparray2 = np.array([[1, 1], [2, 2], [3, 3]]) # Define a 3 x 2 matrix. 

normByCols = np.linalg.norm(nparray2, axis=0) # Get the norm for each column. Returns 2 elements
normByRows = np.linalg.norm(nparray2, axis=1) # get the norm for each row. Returns 3 elements

print(normByCols)
print(normByRows)

[3.74165739 3.74165739]
[1.41421356 2.82842712 4.24264069]


**The dot product between arrays: All the flavors**

In [20]:
nparray1 = np.array([0, 1, 2, 3]) # Define an array
nparray2 = np.array([4, 5, 6, 7]) # Define an array

flavor1 = np.dot(nparray1, nparray2) # Recommended way
print(flavor1)

flavor2 = np.sum(nparray1 * nparray2) # Ok way
print(flavor2)

flavor3 = nparray1 @ nparray2         # Geeks way
print(flavor3)

38
38
38


**Sums by rows or columns**

Another general operation performed on matrices is the sum by rows or columns. Just as we did for the function norm, the axis parameter controls the form of the operation:

1. axis=0 means to sum the elements of each column together.

2. axis=1 means to sum the elements of each row together.

In [21]:
nparray2 = np.array([[1, -1], [2, -2], [3, -3]]) # Define a 3 x 2 matrix. 

sumByCols = np.sum(nparray2, axis=0) # Get the sum for each column. Returns 2 elements
sumByRows = np.sum(nparray2, axis=1) # get the sum for each row. Returns 3 elements

print('Sum by columns: ')
print(sumByCols)
print('Sum by rows:')
print(sumByRows)

Sum by columns: 
[ 6 -6]
Sum by rows:
[0 0 0]


**Get the mean by rows or columns**

In [22]:
nparray2 = np.array([[1, -1], [2, -2], [3, -3]]) # Define a 3 x 2 matrix. Chosen to be a matrix with 0 mean

mean = np.mean(nparray2) # Get the mean for the whole matrix
meanByCols = np.mean(nparray2, axis=0) # Get the mean for each column. Returns 2 elements
meanByRows = np.mean(nparray2, axis=1) # get the mean for each row. Returns 3 elements

print('Matrix mean: ')
print(mean)
print('Mean by columns: ')
print(meanByCols)
print('Mean by rows:')
print(meanByRows)

Matrix mean: 
0.0
Mean by columns: 
[ 2. -2.]
Mean by rows:
[0. 0. 0.]


In [23]:
nparray2 = np.array([[1, -1], [2, -2], [3, -3]])
nparray2 * nparray2

array([[1, 1],
       [4, 4],
       [9, 9]])

In [27]:
np.sum(nparray2 * nparray2, axis = 0)

array([14, 14])